version: '3'
services:
  app:
    container_name: authentication
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes: 
      - ./initMongo:/docker-entrypoint-initdb.d/
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123456
    ports:
      - '27017:27017'
   
